//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

namespace VGMToolbox.tools.extract
{

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class VfsExtractorSettings
    {

        private Header headerField;

        private HeaderParameters headerParametersField;

        private FileRecordParameters fileRecordParametersField;

        private string notesOrWarningsField;

        /// <remarks/>
        public Header Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        public HeaderParameters HeaderParameters
        {
            get
            {
                return this.headerParametersField;
            }
            set
            {
                this.headerParametersField = value;
            }
        }

        /// <remarks/>
        public FileRecordParameters FileRecordParameters
        {
            get
            {
                return this.fileRecordParametersField;
            }
            set
            {
                this.fileRecordParametersField = value;
            }
        }

        /// <remarks/>
        public string NotesOrWarnings
        {
            get
            {
                return this.notesOrWarningsField;
            }
            set
            {
                this.notesOrWarningsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FileRecordParameters
    {

        private string fileRecordsStartOffsetField;

        private string fileRecordSizeField;

        private FileOffsetLengthMethod fileOffsetMethodField;

        private string fileOffsetOffsetField;

        private string fileOffsetOffsetSizeField;

        private Endianness fileOffsetOffsetEndianessField;

        private bool fileOffsetOffsetEndianessFieldSpecified;

        private string fileOffsetOffsetMultiplierField;

        private string fileOffsetCalculationField;

        private string fileCutStartOffsetField;

        private FileOffsetLengthMethod fileLengthMethodField;

        private string fileLengthOffsetField;

        private string fileLengthOffsetSizeField;

        private Endianness fileLengthOffsetEndianessField;

        private bool fileLengthOffsetEndianessFieldSpecified;

        private string fileLengthMultiplierField;

        private string fileLengthCalculationField;

        private bool extractFileNameField;

        private NameLocationType fileNameLocationTypeField;

        private bool fileNameLocationTypeFieldSpecified;

        private string fileNameOffsetField;

        private string fileNameAbsoluteOffsetOffsetField;

        private string fileNameAbsoluteOffsetSizeField;

        private Endianness fileNameAbsoluteOffsetEndianessField;

        private bool fileNameAbsoluteOffsetEndianessFieldSpecified;

        private string fileNameRelativeOffsetOffsetField;

        private string fileNameRelativeOffsetSizeField;

        private Endianness fileNameRelativeOffsetEndianessField;

        private bool fileNameRelativeOffsetEndianessFieldSpecified;

        private RelativeLocationType fileNameRelativeOffsetLocationField;

        private bool fileNameRelativeOffsetLocationFieldSpecified;

        private NameLengthType fileNameLengthMethodField;

        private bool fileNameLengthMethodFieldSpecified;

        private string fileNameSizeField;

        private string fileNameTerminatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileRecordsStartOffset
        {
            get
            {
                return this.fileRecordsStartOffsetField;
            }
            set
            {
                this.fileRecordsStartOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileRecordSize
        {
            get
            {
                return this.fileRecordSizeField;
            }
            set
            {
                this.fileRecordSizeField = value;
            }
        }

        /// <remarks/>
        public FileOffsetLengthMethod FileOffsetMethod
        {
            get
            {
                return this.fileOffsetMethodField;
            }
            set
            {
                this.fileOffsetMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileOffsetOffset
        {
            get
            {
                return this.fileOffsetOffsetField;
            }
            set
            {
                this.fileOffsetOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileOffsetOffsetSize
        {
            get
            {
                return this.fileOffsetOffsetSizeField;
            }
            set
            {
                this.fileOffsetOffsetSizeField = value;
            }
        }

        /// <remarks/>
        public Endianness FileOffsetOffsetEndianess
        {
            get
            {
                return this.fileOffsetOffsetEndianessField;
            }
            set
            {
                this.fileOffsetOffsetEndianessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileOffsetOffsetEndianessSpecified
        {
            get
            {
                return this.fileOffsetOffsetEndianessFieldSpecified;
            }
            set
            {
                this.fileOffsetOffsetEndianessFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileOffsetOffsetMultiplier
        {
            get
            {
                return this.fileOffsetOffsetMultiplierField;
            }
            set
            {
                this.fileOffsetOffsetMultiplierField = value;
            }
        }

        /// <remarks/>
        public string FileOffsetCalculation
        {
            get
            {
                return this.fileOffsetCalculationField;
            }
            set
            {
                this.fileOffsetCalculationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileCutStartOffset
        {
            get
            {
                return this.fileCutStartOffsetField;
            }
            set
            {
                this.fileCutStartOffsetField = value;
            }
        }

        /// <remarks/>
        public FileOffsetLengthMethod FileLengthMethod
        {
            get
            {
                return this.fileLengthMethodField;
            }
            set
            {
                this.fileLengthMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileLengthOffset
        {
            get
            {
                return this.fileLengthOffsetField;
            }
            set
            {
                this.fileLengthOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileLengthOffsetSize
        {
            get
            {
                return this.fileLengthOffsetSizeField;
            }
            set
            {
                this.fileLengthOffsetSizeField = value;
            }
        }

        /// <remarks/>
        public Endianness FileLengthOffsetEndianess
        {
            get
            {
                return this.fileLengthOffsetEndianessField;
            }
            set
            {
                this.fileLengthOffsetEndianessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileLengthOffsetEndianessSpecified
        {
            get
            {
                return this.fileLengthOffsetEndianessFieldSpecified;
            }
            set
            {
                this.fileLengthOffsetEndianessFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileLengthMultiplier
        {
            get
            {
                return this.fileLengthMultiplierField;
            }
            set
            {
                this.fileLengthMultiplierField = value;
            }
        }

        /// <remarks/>
        public string FileLengthCalculation
        {
            get
            {
                return this.fileLengthCalculationField;
            }
            set
            {
                this.fileLengthCalculationField = value;
            }
        }

        /// <remarks/>
        public bool ExtractFileName
        {
            get
            {
                return this.extractFileNameField;
            }
            set
            {
                this.extractFileNameField = value;
            }
        }

        /// <remarks/>
        public NameLocationType FileNameLocationType
        {
            get
            {
                return this.fileNameLocationTypeField;
            }
            set
            {
                this.fileNameLocationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileNameLocationTypeSpecified
        {
            get
            {
                return this.fileNameLocationTypeFieldSpecified;
            }
            set
            {
                this.fileNameLocationTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileNameOffset
        {
            get
            {
                return this.fileNameOffsetField;
            }
            set
            {
                this.fileNameOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileNameAbsoluteOffsetOffset
        {
            get
            {
                return this.fileNameAbsoluteOffsetOffsetField;
            }
            set
            {
                this.fileNameAbsoluteOffsetOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileNameAbsoluteOffsetSize
        {
            get
            {
                return this.fileNameAbsoluteOffsetSizeField;
            }
            set
            {
                this.fileNameAbsoluteOffsetSizeField = value;
            }
        }

        /// <remarks/>
        public Endianness FileNameAbsoluteOffsetEndianess
        {
            get
            {
                return this.fileNameAbsoluteOffsetEndianessField;
            }
            set
            {
                this.fileNameAbsoluteOffsetEndianessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileNameAbsoluteOffsetEndianessSpecified
        {
            get
            {
                return this.fileNameAbsoluteOffsetEndianessFieldSpecified;
            }
            set
            {
                this.fileNameAbsoluteOffsetEndianessFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileNameRelativeOffsetOffset
        {
            get
            {
                return this.fileNameRelativeOffsetOffsetField;
            }
            set
            {
                this.fileNameRelativeOffsetOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileNameRelativeOffsetSize
        {
            get
            {
                return this.fileNameRelativeOffsetSizeField;
            }
            set
            {
                this.fileNameRelativeOffsetSizeField = value;
            }
        }

        /// <remarks/>
        public Endianness FileNameRelativeOffsetEndianess
        {
            get
            {
                return this.fileNameRelativeOffsetEndianessField;
            }
            set
            {
                this.fileNameRelativeOffsetEndianessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileNameRelativeOffsetEndianessSpecified
        {
            get
            {
                return this.fileNameRelativeOffsetEndianessFieldSpecified;
            }
            set
            {
                this.fileNameRelativeOffsetEndianessFieldSpecified = value;
            }
        }

        /// <remarks/>
        public RelativeLocationType FileNameRelativeOffsetLocation
        {
            get
            {
                return this.fileNameRelativeOffsetLocationField;
            }
            set
            {
                this.fileNameRelativeOffsetLocationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileNameRelativeOffsetLocationSpecified
        {
            get
            {
                return this.fileNameRelativeOffsetLocationFieldSpecified;
            }
            set
            {
                this.fileNameRelativeOffsetLocationFieldSpecified = value;
            }
        }

        /// <remarks/>
        public NameLengthType FileNameLengthMethod
        {
            get
            {
                return this.fileNameLengthMethodField;
            }
            set
            {
                this.fileNameLengthMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileNameLengthMethodSpecified
        {
            get
            {
                return this.fileNameLengthMethodFieldSpecified;
            }
            set
            {
                this.fileNameLengthMethodFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileNameSize
        {
            get
            {
                return this.fileNameSizeField;
            }
            set
            {
                this.fileNameSizeField = value;
            }
        }

        /// <remarks/>
        public string FileNameTerminator
        {
            get
            {
                return this.fileNameTerminatorField;
            }
            set
            {
                this.fileNameTerminatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum FileOffsetLengthMethod
    {

        /// <remarks/>
        offset,

        /// <remarks/>
        length,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum NameLocationType
    {

        /// <remarks/>
        fileRecord,

        /// <remarks/>
        absoluteOffset,

        /// <remarks/>
        relativeOffset,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum RelativeLocationType
    {

        /// <remarks/>
        fileRecordStart,

        /// <remarks/>
        fileRecordEnd,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum NameLengthType
    {

        /// <remarks/>
        staticSize,

        /// <remarks/>
        terminator,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HeaderParameters
    {

        private HeaderSizeMethod headerSizeMethodField;

        private string headerEndsAtOffsetField;

        private string headerSizeOffsetField;

        private string headerSizeOffsetSizeField;

        private Endianness headerSizeOffsetEndianessField;

        private bool headerSizeOffsetEndianessFieldSpecified;

        private string fileCountValueField;

        private string fileCountOffsetField;

        private string fileCountOffsetSizeField;

        private Endianness fileCountOffsetEndianessField;

        private bool fileCountOffsetEndianessFieldSpecified;

        /// <remarks/>
        public HeaderSizeMethod HeaderSizeMethod
        {
            get
            {
                return this.headerSizeMethodField;
            }
            set
            {
                this.headerSizeMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string HeaderEndsAtOffset
        {
            get
            {
                return this.headerEndsAtOffsetField;
            }
            set
            {
                this.headerEndsAtOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string HeaderSizeOffset
        {
            get
            {
                return this.headerSizeOffsetField;
            }
            set
            {
                this.headerSizeOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string HeaderSizeOffsetSize
        {
            get
            {
                return this.headerSizeOffsetSizeField;
            }
            set
            {
                this.headerSizeOffsetSizeField = value;
            }
        }

        /// <remarks/>
        public Endianness HeaderSizeOffsetEndianess
        {
            get
            {
                return this.headerSizeOffsetEndianessField;
            }
            set
            {
                this.headerSizeOffsetEndianessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeaderSizeOffsetEndianessSpecified
        {
            get
            {
                return this.headerSizeOffsetEndianessFieldSpecified;
            }
            set
            {
                this.headerSizeOffsetEndianessFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileCountValue
        {
            get
            {
                return this.fileCountValueField;
            }
            set
            {
                this.fileCountValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileCountOffset
        {
            get
            {
                return this.fileCountOffsetField;
            }
            set
            {
                this.fileCountOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string FileCountOffsetSize
        {
            get
            {
                return this.fileCountOffsetSizeField;
            }
            set
            {
                this.fileCountOffsetSizeField = value;
            }
        }

        /// <remarks/>
        public Endianness FileCountOffsetEndianess
        {
            get
            {
                return this.fileCountOffsetEndianessField;
            }
            set
            {
                this.fileCountOffsetEndianessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileCountOffsetEndianessSpecified
        {
            get
            {
                return this.fileCountOffsetEndianessFieldSpecified;
            }
            set
            {
                this.fileCountOffsetEndianessFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum HeaderSizeMethod
    {

        /// <remarks/>
        HeaderSizeValue,

        /// <remarks/>
        HeaderSizeOffset,

        /// <remarks/>
        FileCountValue,

        /// <remarks/>
        FileCountOffset,

        /// <remarks/>
        ReadHeaderToEof,
    }

}